# Generated by Django 5.2.4 on 2025-08-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='user',
        ),
    ]
