# Generated by Django 5.2.4 on 2025-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work_1',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_tag',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
