# Generated by Django 5.2.4 on 2025-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0002_profile_address_profile_hobbies_profile_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work_1',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
