# Generated by Django 5.2.4 on 2025-08-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0003_alter_profile_address_alter_profile_hobbies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_work_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prof_tag',
        ),
    ]
