# Generated by Django 5.2.4 on 2025-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0004_remove_profile_address_remove_profile_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work_1',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_tag',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
